#!/bin/bash

PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin

PLAYLIST_DIR=playlists

ls -1 "$PLAYLIST_DIR/" | fgrep .m3u | while read playlist; do
	echo cmus-remote -C "pl-import $PWD/$PLAYLIST_DIR/$playlist"
	cmus-remote -C "pl-import $PWD/$PLAYLIST_DIR/$playlist"
done

